export const HARD_AI_ML_EXEMPLAR_ANSWERS = Object.freeze([
  {
    id: "mlai-fde-h01",
    version: 1,
    answer: `A strong offline result is evidence for a hypothesis, not a guarantee of online impact. First verify that offline and online objectives actually match. A ranking metric computed on historical clicks may reward engagement while the product needs successful task completion, retention, or revenue. Average gains may also hide regressions for important regions, devices, cohorts, or cold-start items. Leakage, duplicate entities across splits, an unrealistic random split, label-window mistakes, and tuning on the test set can all inflate offline estimates. Delayed or selectively observed labels can make both the baseline and challenger measurements misleading.

Next audit the data and implementation boundary. Compare training, replay, shadow, and live feature distributions, definitions, freshness, missingness, preprocessing, and model versions. Train-serving skew can arise when online feature code differs from the batch pipeline or when a feature is unavailable at decision time. Distribution shift may make historical examples unrepresentative. Trace identical recorded requests through offline and production paths and compare features, predictions, eligibility filters, post-processing, fallbacks, caches, and downstream business rules. Confirm logging joins, exposure identifiers, timestamps, randomization units, and metric denominators. A model can be better yet have no effect because its output is ignored, clipped, stale, routed to little traffic, or dominated by another stage.

Investigate with prioritized, falsifiable tests. Recompute metrics from immutable raw logs, slice results by time and operationally meaningful cohorts, and reproduce the deployed baseline with a point-in-time-correct replay. Shadow both models on current traffic to compare predictions, latency, failure rates, and disagreement without affecting users. Then canary the challenger behind a kill switch, checking guardrails and whether treatment assignment changes the intended decision. Use a randomized controlled experiment with a predeclared primary metric, power analysis, stable assignment, and enough time for delayed outcomes and novelty effects. Diagnose treatment interference if one user's treatment changes another user's inventory or experience. Logged correlation alone does not establish causal impact; use randomization or justified causal methods when randomization is impossible.

Feedback loops deserve separate analysis because deployment changes what is later observed. A recommender promotes selected items, receives labels mainly for those exposures, and may amplify popularity while suppressing evidence about alternatives. Fraud blocking prevents outcomes from being observed; human reviewers adapt; users and suppliers respond. Retraining on this selected data can reinforce the deployed policy rather than fix it automatically. Preserve randomized exploration traffic or propensity information where safe, measure exposure and label coverage, and evaluate off-policy assumptions carefully.

Finally, reconcile findings by layer and decision: data validity, offline metric validity, model behavior, integration, serving, and causal product effect. Assign each hypothesis an owner, diagnostic, expected signature, and stop condition. Promote only after the canary and controlled experiment show meaningful improvement with acceptable safety, fairness, reliability, latency, and cost; otherwise roll back while retaining artifacts for analysis. Document negative results too, because they refine the causal model and prevent repeated failures. If exploration is constrained, quantify unsupported regions and avoid extrapolating beyond observed overlap. Recheck novelty, seasonality, and network effects over longer horizons before declaring equivalence or abandoning it.`,
  },
  {
    id: "mlai-fde-h02",
    version: 1,
    answer: `Sparse, dense, and reranking stages solve different retrieval problems. A sparse method such as BM25 represents queries and documents through terms and weighted term frequencies. It excels when exact wording matters: product codes, error messages, names, legal phrases, rare identifiers, and user-supplied quotations. Its scores are interpretable and inverted indexes are efficient, but vocabulary mismatch and paraphrases can reduce recall. Dense retrieval embeds queries and documents into learned vectors and searches for nearby representations. It can retrieve semantically related passages with little lexical overlap, but quality depends on training data and domain fit; it may blur crucial numbers, negation, or rare tokens and adds embedding, index, and refresh costs. Neither method makes the other obsolete.

A hybrid system runs both retrievers, normally after applying mandatory tenant, access-control, language, date, and document-type filters in a way that cannot be bypassed by later stages. It collects a sufficiently broad candidate set from each source, deduplicates by stable document or chunk identity, and fuses evidence. Raw BM25 and cosine scores are not directly comparable, so calibrated score normalization or rank-based methods are preferable. Reciprocal-rank fusion, for example, sums a decreasing contribution based on each result's rank and is robust to score-scale differences. Fusion improves recall because an item missed by one representation may be supplied by the other, while weights can reflect domain priorities.

The fused top candidates then enter a more expensive reranker. A cross-encoder or constrained language model jointly examines the query and each candidate, capturing fine interactions, context, and task-specific relevance better than independent embeddings. It should score tens or hundreds of candidates, not the entire corpus, because its computation grows with candidate count and sequence length. Crucially, reranking can reorder only documents that retrieval included; it cannot recover an excluded relevant document. Candidate recall therefore sets the quality ceiling, while the reranker mainly improves precision and ordering near the top.

Tune each stage with stage-appropriate evidence. Measure sparse recall, dense recall, their overlap, union recall, and recall at the reranker input against judged queries. Measure final NDCG, MRR, precision, answer-support coverage, and downstream task success after reranking. Slice by identifier queries, paraphrases, languages, freshness, and protected access classes. Also track p50 and tail latency, query and indexing compute, memory, embedding freshness, cache behavior, and authorization failures. Ablations reveal whether gains come from dense retrieval, fusion, or reranking rather than from a changed candidate budget.

Tradeoffs are explicit. Larger candidate pools raise recall but increase network traffic and reranking latency. Stronger rerankers improve precision but cost more, complicate deployment, and may time out; bounded fallbacks should return the fused ranking safely. Dense indexes require re-embedding after model changes, while sparse indexes update cheaply. Fusion adds parameters and operational complexity. Version embeddings, indexes, filters, fusion settings, and rerankers together; shadow changes, canary them, monitor drift, and retain a lexical fallback. The best design meets a measured quality target under latency, cost, freshness, and security constraints, rather than maximizing one benchmark in isolation. Document rejected alternatives so future tuning remains evidence driven.`,
  },
  {
    id: "mlai-fde-h03",
    version: 1,
    answer: `An LLM judge is a measurement instrument, not an objective oracle. It can prefer the first or second answer because of position, reward verbosity or polished style rather than correctness, favor outputs resembling its own model family, and apply a rubric inconsistently across topics. Sampling and serving changes introduce nondeterminism, while ambiguous prompts cause unstable interpretation even at low temperature. Persuasive explanations can mask factual errors. Answers may also contain prompt injection that asks the judge to ignore criteria, reveal hidden material, or assign a score. Numeric output and fluent rationale do not prove validity, and low temperature cannot remove systematic bias.

Begin by defining the construct being measured. Write criterion-specific descriptions, anchored examples, disqualifying errors, score ranges, and an explicit aggregation rule. Keep irrelevant stylistic preferences out unless style is genuinely part of the task. Present candidate answers anonymously, strip authorship and model identifiers, normalize inconsequential formatting, and randomize order. Delimit answers as untrusted data in a strict structured prompt, state that embedded instructions have no authority, keep rubric material outside answer-controlled fields, and validate the returned schema and score bounds. Use deterministic blank and tie rules in application code rather than delegating them ambiguously.

Calibration requires a representative, blinded human-scored set spanning difficulty, quality, domains, languages, edge cases, adversarial injections, and near ties. Multiple trained raters should score independently under the same rubric; adjudicate disagreements without seeing the model judge's verdict. Measure human-human agreement to establish the achievable ceiling, then compare judge-human criterion scores, total-score error, rank agreement, classification precision and recall at decision thresholds, and calibration by score band. Do not rely on one aggregate correlation, which can look strong while important slices or pairwise decisions fail.

Run controlled robustness experiments. Score every pair in both orders and report flip rate and position-conditioned deltas. Repeat identical cases across runs, seeds, dates, and model versions to measure stability. Create matched answers that vary only in length, confidence, formatting, or model-associated style; scores should remain invariant unless the rubric warrants a difference. Include known factual traps, paraphrases, injected instructions, irrelevant eloquence, and swapped identities. Compare direct scoring with pairwise judging, and consider an ensemble of diverse judges or repeated votes when measured benefits justify added cost. Route uncertain, high-impact, or disagreement cases to blinded human adjudication.

Operational hardening continues after launch. Version the prompt, rubric, provider model, decoding settings, parser, and calibration set. Log hashes, scores, order, latency, and decision outcomes without exposing private answers or identities unnecessarily. Audit random samples and high-loss slices, monitor agreement, score distributions, order sensitivity, refusal rates, and drift against stable human checkpoints. Set release gates and rollback thresholds before upgrades. Investigate calibration drift when content or candidate models change, because a judge validated on one distribution may fail on another.

Finally, use the judge only within its validated scope. Report uncertainty and known slice limitations, preserve human appeals for consequential decisions, and periodically refresh adversarial tests. The defensible claim is measured agreement under stated conditions, not universal objectivity. Revalidate after every material change.`,
  },
  {
    id: "mlai-fde-h04",
    version: 1,
    answer: `Fine-tuning changes a model to reduce loss on an adaptation distribution. That can improve a specialized task while degrading other abilities because gradient updates optimize the sampled objective, not every behavior the base model previously supported. A narrow or repetitive dataset can overemphasize domain vocabulary, formats, or policies and produce over-specialization. Updates may overwrite parameters useful for general reasoning or unrelated knowledge, a form of catastrophic forgetting. Distribution mismatch, noisy labels, duplicated examples, spurious cues, and preference objectives that reward superficial compliance can further shift behavior. More examples are not automatically beneficial when their quality, diversity, or weighting is poor.

Data design is the first control. Define the target behavior and failure taxonomy, deduplicate and audit labels, cover difficulty and edge cases, and reserve untouched target evaluation sets. Mix representative retention data for general instruction following, reasoning, multilingual use, safety, and important legacy workflows into training. Balance sampling so abundant easy examples do not dominate rare critical cases. A curriculum or stratified batches can maintain coverage throughout optimization rather than appending retention examples after forgetting occurs.

Constrain the update. Use a conservative learning rate, limited epochs, early stopping on both target and retention metrics, weight decay or explicit regularization toward base parameters, and checkpoint selection based on a multi-objective score. Parameter-efficient adapters or low-rank updates isolate changes, reduce storage, and make disabling or rolling back an adaptation easier. However, adapters still alter activations and can regress behavior, so parameter efficiency is not a safety guarantee. If preference tuning is used, control reward hacking and excessive divergence with reference-model regularization and evaluate whether helpful specialization trades away honesty or refusal behavior.

Prove improvement with a preregistered comparison against the exact original model and relevant prompting or retrieval baselines. On the target task, use held-out examples, meaningful task metrics, blinded human review where needed, confidence intervals, and slices by difficulty, user group, topic, and input length. Check contamination and run adversarial cases that expose shortcuts. Measure latency, memory, and cost because an accuracy gain that breaks service constraints may not be deployable. Repeat evaluations across seeds or checkpoints when variance matters.

The retention suite is equally important. Re-run capability benchmarks, production regression cases, tool-use and structured-output contracts, safety policies, calibration, hallucination or abstention behavior, and out-of-domain prompts. Compare absolute results and deltas with predefined noninferiority bounds, not merely averages; a stable mean can hide a severe safety or minority-language regression. Include red-team tests tailored to the new domain, since specialization may create novel misuse paths. Human raters should be blinded to model identity to reduce expectation bias.

Deploy through shadow traffic and a small canary, monitoring target quality plus retained capabilities, refusals, errors, drift, and user outcomes. Version data, code, base checkpoint, adapter, and evaluation artifacts. Keep the base route available for rollback or selective routing. If target gains exceed their threshold but any critical retention guardrail fails, revise the data mixture or optimization and retest. The adapted model is better only when measured specialization benefits outweigh regressions within explicit risk tolerances.`,
  },
  {
    id: "mlai-fde-h05",
    version: 1,
    answer: `Treat a model release as a versioned system change, not a weights swap. Create one immutable release manifest containing the model artifact and tokenizer, prompts and templates, feature definitions, preprocessing, retrieval indexes, tool specifications, output schema, safety policies, runtime image, libraries, and relevant service dependencies. Record training data lineage, evaluations, configuration, and checksums. Give requests and outputs explicit schema versions, and namespace caches by every input that can affect semantics so old responses are never silently served as new behavior.

Start with compatibility design. Inventory every producer and consumer, including asynchronous jobs, stored state, analytics, and human workflows. Define contracts for types, required fields, ranges, ordering, error semantics, latency, and safety behavior. Run consumer-driven contract tests and golden fixtures against both versions. Prefer additive, backward-compatible schema changes; use adapters or dual readers and writers during transitions. Validate database and state migrations on production-shaped copies, including downgrade behavior. Keep state backward-compatible throughout the rollback window.

Build preproduction evidence before exposure. Reproduce baseline metrics, replay representative and adversarial logged inputs with point-in-time features, and compare quality, safety, calibration, latency, throughput, errors, and cost by slice. Run load, fault, timeout, and dependency compatibility tests. Then shadow the challenger on live traffic without using its outputs, checking feature parity, prediction disagreement, tail latency, resource demand, and downstream contract validity. Protect sensitive logs and ensure shadow calls cannot trigger external side effects.

Release behind a feature flag or champion-challenger router with an immediate server-side kill switch. Begin with internal traffic, then a small randomized canary whose assignment is stable and whose blast radius is bounded by tenant, region, and use case. Exclude workflows that cannot yet consume the version safely. Predeclare promotion gates, observation windows, minimum sample sizes, and stop conditions. Expand gradually only after each gate passes; do not let aggregate success hide a critical slice.

Observe both infrastructure and model behavior. Dashboards and alerts should cover availability, error and fallback rates, p50 and tail latency, saturation, queueing, token use, and cost, plus task quality, hallucination or grounding failures, policy violations, refusal behavior, calibration, schema validity, and downstream business outcomes. Compare treatment with the concurrent champion to separate release effects from traffic changes. Assign named owners for monitoring, approval, incident command, and rollback. Trace model, prompt, feature, cache, and dependency versions per request.

Practice rollback before launch. The rollback procedure should atomically route traffic to the champion, restore compatible prompts and features, isolate challenger cache entries, stop incompatible writes, and reverse or forward-fix state safely. Test it under load and measure recovery time. Preserve idempotency for retries and prevent retry storms when dependencies fail. If a guardrail breaches, freeze expansion, capture diagnostics, and execute the documented rollback without waiting for broad statistical significance on a safety incident.

After full exposure, retain a holdback where appropriate, continue drift and outcome monitoring, reconcile delayed labels, and conduct a release review. Remove compatibility paths only after the rollback horizon and stored-state audit pass. This staged, observable process makes promotion evidence-based and rollback genuinely operational rather than aspirational.`,
  },
  {
    id: "mlai-fde-h06",
    version: 1,
    answer: `Calibration links stated probabilities to empirical frequencies. Among predictions assigned approximately 0.8 probability under comparable conditions, about 80 percent should be correct in the long run. This is different from accuracy: a model can be accurate but overconfident, or less accurate yet well calibrated. Calibration also does not ensure that any individual prediction is correct. It is a distributional property of a model, task, population, labeling process, and time period, so it must be evaluated on representative data and can deteriorate under distribution shift.

Measure it using held-out, point-in-time examples that match deployment, with trustworthy labels and enough samples for important slices. Reliability diagrams compare average confidence with observed frequency in probability bins; expected calibration error summarizes gaps but depends on binning and can hide local failures. Also inspect maximum calibration error, Brier score or log loss, classwise and subgroup diagrams, and confidence distributions. Estimate uncertainty with bootstrap intervals. Recalibrate and monitor when prevalence, sensors, users, or model versions change.

Uncertainty estimates can drive safer actions when their validity is measured. Predictive probabilities, ensembles, Bayesian approximations, model disagreement, retrieval support, or out-of-distribution signals capture different uncertainties and have different failure modes. Low disagreement does not prove truth when models share data or biases. Separate aleatoric uncertainty, arising from irreducible ambiguity, from epistemic uncertainty that may fall with better knowledge, when that distinction informs action. Validate every signal against errors and costly outcomes rather than assuming a softmax value is trustworthy.

An abstaining system answers only when a risk or uncertainty rule is satisfied and otherwise defers, requests more information, invokes a verified tool, or sends the case to a human. Evaluate coverage, the fraction answered, together with selective risk, the error rate among answered cases, across thresholds and slices. Raising the threshold generally reduces coverage and may lower risk, but can disproportionately defer certain populations, increase workload, or delay service. Choose an operating point from explicit error costs, review capacity, and service-level requirements, and test the fallback itself. Abstention therefore improves safety through a measured coverage-risk tradeoff, not for free.

Conformal prediction can produce prediction sets or intervals with finite-sample coverage under exchangeability assumptions, using a held-out calibration set. Its guarantee is marginal rather than automatically per subgroup, and shift can invalidate it; set size communicates difficulty but does not explain causality. Selective classification and risk-controlling methods likewise require assumptions and fresh validation. Monitor label-delayed outcomes, coverage, selective risk, subgroup behavior, and drift, with triggers for recalibration or a safer default.

An LLM saying “I am 95 percent confident” is generating plausible text conditioned on its prompt. That number is not automatically tied to observed correctness, may change with wording, and can remain confident when unsupported. Token probabilities describe next-token likelihood, not directly the truth of a completed claim. To use confidence operationally, define the event being predicted, elicit a reproducible score, calibrate it empirically on representative tasks, test it under shift, and combine it with evidence checks or external verification. Communicate residual uncertainty and preserve escalation for high-consequence decisions.`,
  },
] as const);
