export const MEDIUM_AI_ML_EXEMPLAR_ANSWERS = Object.freeze([
  {
    id: "mlai-fde-m01",
    version: 1,
    answer: `Data leakage occurs when model development uses information that would not be available when a real prediction is made. The leaked signal need not be the target column itself. Any feature, transformation, split decision, or selection process that transfers future, test, or otherwise unavailable information into training can make the learned system look better than it will perform in deployment.

One common mechanism is fitting preprocessing before splitting. If normalization statistics, imputers, feature selectors, PCA, vocabulary construction, or target encodings are learned from the entire dataset, validation and test examples influence the representation given to the model. Even an unsupervised transformation can leak distributional information. Inside cross-validation, every learned transformation must likewise be fitted only on each training fold and then applied unchanged to that fold’s validation portion.

A second mechanism is temporal leakage. A fraud model might use a chargeback status recorded weeks after the transaction, or an aggregate computed with events occurring after prediction time. Point-in-time joins must reconstruct exactly what was known at the decision timestamp. A third mechanism is entity contamination: near-duplicate documents, images from the same patient, or transactions from one customer can land in different splits. The model then recognizes an entity or duplicate instead of generalizing. Grouped, deduplicated, or time-ordered splits are often required; a random row split is not automatically safe.

Leakage produces optimistic evaluation because development and evaluation are no longer independent. The validation metric rewards choices that exploit transferred information, while the test metric measures performance on partially seen signals rather than a realistic future population. Repeatedly inspecting the test set also leaks selection information: researchers adapt features, thresholds, and models to its outcomes even without training directly on its rows.

Prevention starts by defining the prediction time, unit of generalization, and deployment data contract. Split first using time, entity, geography, or another structure that matches deployment. Encapsulate preprocessing and modeling in one pipeline, fit every learned component on training data only, and perform hyperparameter selection within leakage-safe cross-validation. Build point-in-time-correct features, deduplicate before splitting, and keep the final representative test set sealed until decisions are complete.

Finally, audit feature provenance and timestamps, search for suspiciously strong variables, compare random and deployment-shaped splits, and reproduce features from production logs. Leakage is a causal availability problem, not merely a high score or a label-column mistake; preventing it requires disciplined boundaries throughout collection, joining, preprocessing, tuning, and evaluation.

Nested validation is useful when the dataset is small: inner folds select preprocessing and hyperparameters, while outer folds estimate the entire selection procedure. The outer assessment must still respect groups and time. In production, training-serving parity checks should compare offline feature values with values reconstructed by the online pipeline at identical timestamps. Permissions, data retention, and delayed labels also affect availability. A feature may exist in a warehouse today yet have been unavailable when the decision occurred. Documenting feature creation times, event times, update delays, and lineage makes that distinction testable. These controls preserve honest estimates and prevent leakage from returning as pipelines evolve.`,
  },
  {
    id: "mlai-fde-m02",
    version: 1,
    answer: `Accuracy can hide failure when classes are imbalanced. If one percent of transactions are fraudulent, a classifier that always predicts “legitimate” is ninety-nine percent accurate while detecting no fraud. The useful question is therefore not how often any label is correct, but which false positives and false negatives occur, for whom, and at what operational cost.

I would begin with the confusion matrix and the application’s consequences. Recall measures the fraction of actual positives found and matters when missed positives are costly. Precision measures how many alerts are truly positive and matters when investigations or interventions are expensive. Specificity and false-positive rate describe burden on the negative class. An F-beta score can emphasize recall or precision, but its weighting must reflect the decision. A precision-recall curve and PR-AUC are often more informative than accuracy, and usually more revealing than ROC-AUC under severe imbalance, because they expose performance on the rare class across thresholds. Neither curve selects a threshold by itself.

Metric choice should follow explicit costs and capacity. For example, choose a threshold on validation data that maximizes expected value, meets a minimum recall, or limits alerts to the review team’s capacity. Report precision, recall, and cost at that operating point, along with confusion counts. Examine results across important slices such as geography, device, demographic group, or event subtype; an acceptable aggregate can conceal a failed minority slice. Check probability calibration if scores drive risk estimates or downstream decisions, since ranking quality and calibrated probability are different properties.

Improvements must be learned without contaminating evaluation. On training data, I could use class-weighted or cost-sensitive loss, focal loss, collect more representative minority examples, improve labels and features, or resample the minority or majority class. Resampling belongs inside each training fold, after splitting; doing it before splitting can duplicate observations into validation. I would compare models and thresholds on validation data and, if necessary, calibrate probabilities using separate validation data or properly nested cross-validation.

The final test set should remain untouched, preserve the deployment prevalence and meaningful grouping or time structure, and receive exactly one final evaluation after choices are frozen. Artificially balancing the test set may answer a diagnostic question, but it cannot estimate real-world precision without correction because precision changes with prevalence. If deployment prevalence changes, monitor calibration, alert volume, precision when labels arrive, and slice metrics, then revisit thresholds using a new validation window rather than tuning on the test result.

Thus there is no universally best metric or intervention. A defensible system links errors to costs, evaluates ranking and thresholded behavior, protects a representative test set, and reports uncertainty and subgroup behavior alongside any headline number.

Uncertainty around metrics matters as well. Use confidence intervals or repeated, grouped resampling that preserves dependence, especially when the positive test count is small. Compare candidates on paired examples, document the chosen operating rule before opening the test set, and report raw counts so apparently large percentage changes are interpretable. Post-deployment labels should update monitoring datasets, not retroactively alter the frozen evaluation.`,
  },
  {
    id: "mlai-fde-m03",
    version: 1,
    answer: `Self-attention lets every token construct a new representation by selectively combining information from other tokens. Starting from each token’s current vector, learned projections produce a query, a key, and a value. The query expresses what that position is looking for; keys describe what other positions can match; values contain the information that may be passed along.

For one token, the model compares its query with every permitted key. After scaling and normalization, commonly with a softmax, these compatibility scores become attention weights. The weighted sum of the corresponding value vectors is therefore different for each receiving token. In “The animal did not cross the road because it was tired,” the representation of “it” can incorporate information from “animal,” while another token attends to different context. Attention does not retrieve a symbolic definition; it learns useful patterns because the entire network is optimized for its training objective.

Transformers use multiple attention heads. Each head has separate projections and can represent different relationships, such as local syntax, long-range dependency, entity association, or task-specific cues. Their outputs are concatenated and transformed, then combined with residual connections and feed-forward layers. Heads are not guaranteed to specialize cleanly, and an attention weight is not a definitive causal explanation of a prediction. Attending strongly to a statement also does not make that statement true.

Bare self-attention has no inherent notion of sequence order. If token vectors were permuted, the same operation would permute its outputs correspondingly; query-key comparisons alone do not tell whether one word came before another or how far apart they were. Transformers therefore inject positional information, for example learned absolute embeddings, sinusoidal encodings, relative position biases, or rotary position representations. These signals let the network distinguish order and distance. Autoregressive models additionally apply a causal mask so a position cannot attend to future tokens during next-token prediction; masks restrict visibility, whereas positional representations encode order.

A major limitation is context cost. Full attention compares every position with every other position, requiring quadratic numbers of pairwise scores and substantial memory as sequence length grows. Long contexts can therefore increase latency and accelerator memory dramatically, and useful evidence may still be diluted or poorly used. Local, sparse, sliding-window, compressed, or linearized attention can reduce cost, but each approximation may lose global interactions or introduce architectural complexity. Fixed context windows also exclude material beyond their boundary.

Self-attention is thus a learned, content-dependent communication mechanism: queries and keys determine how strongly information flows, values carry that information, multiple heads provide parallel relationship spaces, and positional signals restore sequence structure. Its flexibility explains the transformer’s contextual representations, while its learned nature, computational scaling, and lack of guaranteed faithfulness or factuality define important limits.

During training, gradients adjust all projections so useful communication patterns emerge jointly with later layers. Computational efficiency does not guarantee reasoning across long distances: models may underuse context despite having room for it. Evaluation should therefore vary distance, distractors, order, and context length, while testing whether causal masking and padding masks prevent forbidden information flow.`,
  },
  {
    id: "mlai-fde-m04",
    version: 1,
    answer: `Training and inference have different goals, so some layers must change behavior when a model switches modes. Training deliberately introduces noise or estimates population information while parameters are being learned. Inference should normally produce stable predictions for individual examples using the behavior assumed during optimization. A framework’s train and evaluation flags coordinate these semantics; disabling gradient computation alone does not necessarily switch the layers.

Dropout randomly sets a fraction of activations to zero during training. This prevents units from depending too heavily on particular collaborators and acts as regularization. Implementations commonly use inverted dropout: retained activations are scaled during training so their expected magnitude already matches inference. During ordinary inference, dropout is disabled and all activations participate without random masking. Leaving dropout active makes repeated predictions for the same input vary and can reduce quality because the deployed network no longer behaves like the expected ensemble used during evaluation. Conversely, disabling dropout during training removes the intended regularization and changes optimization.

Batch normalization has a distinct reason for changing modes. During training it normalizes activations using the current mini-batch’s mean and variance, applies learned scale and offset parameters, and updates running estimates of those statistics. During inference it uses the stored running mean and variance rather than statistics from the current request. This makes a prediction independent of which unrelated examples happen to share its batch and supports batch size one. If batch normalization remains in training mode in production, outputs become batch-composition dependent, small batches yield noisy estimates, repeated traffic can mutate running state, and the activation distribution may shift. If stale or poorly estimated running statistics are used, evaluation can also degrade despite a correct mode setting.

The wrong mode can therefore cause nondeterminism, unstable metrics, train-serving skew, sensitivity to batch size or ordering, and unexpectedly poor calibration. A subtle bug arises when developers call an evaluation loop without switching the model to evaluation mode, or switch modes but forget to restore training afterward. Tests should compare repeated predictions, single-item versus batched predictions, and a known validation set while asserting the model’s mode.

Not every normalization layer behaves like batch normalization. Layer normalization computes statistics within each example and typically has the same train and inference calculation, although the surrounding model can still contain dropout. There are also intentional exceptions: Monte Carlo dropout keeps dropout active across multiple inference passes to estimate variability. That is a designed sampling procedure whose predictions are aggregated, not the default serving behavior.

Reliable deployment saves learned parameters together with batch-normalization buffers, switches explicitly to evaluation mode, disables gradients for efficiency, and verifies deterministic behavior where expected. Correct mode handling preserves the statistical assumptions under which the model was trained while allowing deliberate stochastic inference only when the application explicitly requires and validates it.

Mode correctness depends on data loading and export paths. Validation loaders should not apply training-only augmentation, and exported runtimes preserve layer semantics and buffers. Record preprocessing, checkpoint, framework version, and mode used for benchmarks so execution mismatches remain traceable.`,
  },
  {
    id: "mlai-fde-m05",
    version: 1,
    answer: `A RAG pipeline succeeds only if it retrieves usable evidence and the generator uses that evidence faithfully. I would treat ingestion, candidate retrieval, ranking, context assembly, and generation as separately measurable stages rather than optimize one end-to-end score.

Chunk size controls a focus-versus-context tradeoff. Small chunks often match a narrow query precisely and waste fewer context tokens, but they can separate a claim from definitions, qualifications, tables, or surrounding steps needed to interpret it. Large chunks preserve more local context but mix topics, dilute embedding similarity, consume the model’s context window, and reduce how many sources fit. The right unit should respect document structure and task needs, then be tuned on representative queries rather than selected universally.

Overlap repeats text across adjacent chunks so evidence spanning a boundary appears intact somewhere. Moderate overlap can improve recall, but excessive overlap expands the index, increases embedding and retrieval cost, returns near-duplicates, crowds diverse evidence out of the top results, and wastes generation tokens. Structural splitting, parent-child retrieval, and deduplication can preserve context more efficiently than indiscriminately increasing overlap.

Metadata filtering determines candidate eligibility before or during retrieval. Tenant, authorization, date, language, product, or document-type filters can improve precision, freshness, and security by excluding irrelevant material. Overly strict, missing, or incorrect metadata can eliminate the only relevant document, so filters need coverage tests and safe access-control semantics. Reranking has a different role: after a fast retriever produces a reasonably broad candidate set, a more expensive cross-encoder or model scores query-document pairs and reorders a limited subset. It can improve top-k relevance, but adds latency and compute and cannot recover a document the first stage excluded.

To diagnose retrieval, build queries with document-level relevance labels and measure recall at k, precision at k, ranking metrics such as MRR or nDCG, filter pass rates, duplicate rate, and whether required evidence fits the assembled context. Inspect these by query and content slice. Low recall points toward indexing, chunking, filters, query rewriting, or candidate generation; good candidate recall but poor top ranks points toward scoring or reranking.

To diagnose generation, hold retrieval constant. Give the model known gold evidence or the best retrieved context and evaluate answer correctness, citation accuracy, groundedness, completeness, and unsupported claims. If generation succeeds with gold context but fails end to end, retrieval or packing is responsible. If the needed passage is present yet the answer is wrong or unfaithful, investigate instructions, context ordering, conflicting evidence, model capability, or abstention behavior. Prompting cannot reconstruct missing evidence.

Finally, version the corpus and pipeline, retain stage traces without exposing sensitive text, maintain adversarial and regression queries, and test latency and cost alongside quality. This decomposition reveals whether a change improves candidate coverage, ordering, or evidence use, whereas aggregate answer accuracy alone cannot identify the failing stage.

Context assembly should preserve identity, access policy, and ordering within a token budget. Packing passages, sections, or parent documents trades breadth against depth. Evaluate citations against passages shown, and require abstention when evidence is missing, contradictory, unauthorized, or weak.`,
  },
  {
    id: "mlai-fde-m06",
    version: 1,
    answer: `A robust LLM evaluation suite begins with the application’s decisions and failure costs, not one convenient benchmark. I would maintain a versioned dataset sampled from realistic traffic and expert-designed scenarios, with documented provenance, expected behavior, and important slices such as task type, language, customer, difficulty, risk level, and input length. Training or prompt-development contamination must be tracked, and a sealed holdout should confirm final choices.

Evaluation must span several dimensions. Task-specific correctness and relevance ask whether the response solves the request. Groundedness and citation checks ask whether claims follow from supplied sources. Safety tests cover harmful output, privacy, prompt injection, access boundaries, and appropriate refusal or abstention. Operational metrics include latency distributions, throughput, availability, token use, and monetary cost. Format validity, tool-call correctness, and deterministic business rules should also be measured when applicable. Each metric needs an acceptance threshold tied to product risk.

I would triangulate evaluators. Deterministic assertions are ideal for schemas, exact facts, executable code, citations, permissions, and invariants because they are reproducible. Calibrated model graders can scale nuanced comparisons, but their rubric must be explicit and their outputs validated against blinded human-scored examples. Test agreement, position-order sensitivity, repeat stability, and performance on adversarial inputs; do not treat the grader as ground truth. Trained human reviewers should adjudicate ambiguous, high-impact, and sampled production cases using the same rubric. Measure inter-rater agreement and refine unclear criteria rather than hiding disagreement.

The suite should include fixed regressions for past failures, broad representative samples, rare but severe safety cases, boundary conditions, multilingual and long-context cases, malformed inputs, prompt-injection attempts, and counterfactual or contrast pairs. Run it continuously against versioned models, prompts, tools, retrieval indexes, and policies. Report confidence intervals or paired bootstrap uncertainty where sampling matters, and require both global gates and slice-level non-regression gates.

A single aggregate accuracy can conceal a catastrophic regression in a small safety-critical slice, average together incomparable tasks, ignore calibration and severity, and reward easy frequent examples. A single model-judge score adds grader bias, nondeterminism, rubric inconsistency, model-family preference, and susceptibility to style or injection. Even an improved mean may trade groundedness for fluency, quality for latency, or one population’s performance for another’s.

Before launch, compare candidates on the frozen suite and perform red-team and human review. Then use shadow traffic, canaries, and controlled online experiments to verify that offline metrics predict user outcomes without exposing everyone at once. Monitor drift and newly discovered failures, add sanitized cases to the regression set, and periodically recalibrate graders against humans. The result is an evidence portfolio: reproducible checks, representative metrics, adversarial coverage, calibrated judgment, human oversight, uncertainty, slice analysis, and online confirmation together support a release decision that no solitary score can justify.

Evaluation data needs governance. Track ownership, consent, sensitive attributes, annotation instructions, and expiration; prevent production secrets from entering test tooling. When a metric changes, retain its previous definition or recompute baselines so trends remain meaningful. Release reports should record model and dependency versions, dataset version, thresholds, exceptions, reviewer decisions, and known blind spots for reproducibility.`,
  },
  {
    id: "mlai-fde-m07",
    version: 1,
    answer: `Latency is the time one request takes, while throughput is the amount of work completed per unit time. They interact but are not identical: a server can improve throughput by forming larger batches while making an individual request wait longer. Optimization should start with workload traces, service-level objectives, quality requirements, accelerator utilization, queue time, and p50, p95, and p99 latency rather than averages alone.

Dynamic batching combines requests so matrix operations use hardware efficiently, increasing throughput and often lowering cost per token. Its tradeoff is queueing delay, memory pressure, and interference between long and short requests; bounded batch windows and length-aware scheduling protect latency. Streaming tokens improves time to first visible output but does not necessarily reduce total compute and complicates cancellation and moderation.

Caching exact responses, prompt prefixes, retrieved context, embeddings, or model states can eliminate repeated work. Benefits depend on hit rate. The costs are memory, invalidation, stale answers, tenant isolation, and possible privacy leaks, so keys must include relevant model, prompt, data, authorization, and version information. Quantization reduces memory bandwidth and can permit more replicas or faster inference, but lower precision may reduce quality, especially for sensitive tasks or aggressive bit widths. Benchmark accuracy by slice rather than assume equivalence.

Routing simple requests to a smaller model lowers latency and cost while reserving a larger model for difficult cases. The router itself can make quality errors, needs calibrated escalation criteria, and adds operational complexity. Distillation offers similar efficiency but requires training and may lose rare capabilities. Compilation, optimized kernels, and speculative decoding can accelerate supported workloads, although they add build complexity, hardware constraints, or draft-model memory and do not help every request shape.

Autoscaling matches replicas to demand, but cold starts arrive too late for sudden spikes. Warm capacity reduces tail latency and failure risk at the price of idle cost. Admission control, priorities, bounded queues, and load shedding keep overload from turning into unbounded latency. Capacity planning must account for context length, generated tokens, burstiness, and regional or accelerator failures, not only average requests per second.

Reliability controls are part of performance. Set end-to-end deadlines and per-stage timeouts so abandoned work is cancelled. Retry only transient, idempotent operations with strict limits, exponential backoff, and jitter; unrestricted retries amplify overload and cost. Circuit breakers stop calls to an unhealthy dependency, while fallbacks can use a smaller model, cached result, reduced context, or explicit temporary failure. Validate fallback safety instead of silently returning lower-quality output.

Finally, monitor queue time, time to first token, total latency, token throughput, saturation, cache hit rate, error and timeout rates, retry volume, quality, and cost by model and slice. Load tests and failure drills should verify SLOs at expected peaks. The best design is workload-specific: combine techniques only after measuring their effects on tail latency, throughput, correctness, reliability, memory, and total cost.

Measure end-to-end cost, including idle replicas, storage, transfer, retries, and engineering overhead. Roll out changes through shadow traffic and canaries; speed never excuses violations of quality, safety, fairness, or data-isolation gates.`,
  },
] as const);
